config/routes.rb
Rails.application.routes.draw do
  get 'users/index'

  get 'inicio/index'

  resources :grupos
  devise_for :users
  resources :asignaturas
  root 'inicio#index'

end

app/models/asignatura.rb
class Asignatura < ActiveRecord::Base
    has_many :grupo
    validates :nombre, presence: { message: ": Es necesario un nombre para continuar" }
end

app/controllers/asignaturas_controller.rb
class AsignaturasController < ApplicationController
  load_and_authorize_resource
  before_action :set_asignatura, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /asignaturas
  # GET /asignaturas.json
  def index
    @asignaturas = Asignatura.all.order("nombre asc")
  end

  # GET /asignaturas/1
  # GET /asignaturas/1.json
  def show
  end

  # GET /asignaturas/new
  def new
    @asignatura = Asignatura.new
  end

  # GET /asignaturas/1/edit
  def edit
  end

  # POST /asignaturas
  # POST /asignaturas.json
  def create
    @asignatura = Asignatura.new(asignatura_params)

    respond_to do |format|
      if @asignatura.save
        format.html { redirect_to @asignatura, notice: 'La asignatura ha sido creada.' }
        format.json { render :show, status: :created, location: @asignatura }
      else
        format.html { render :new }
        format.json { render json: @asignatura.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /asignaturas/1
  # PATCH/PUT /asignaturas/1.json
  def update
    respond_to do |format|
      if @asignatura.update(asignatura_params)
        format.html { redirect_to @asignatura, notice: 'La asignatura fue actualizada correctamente.' }
        format.json { render :show, status: :ok, location: @asignatura }
      else
        format.html { render :edit }
        format.json { render json: @asignatura.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /asignaturas/1
  # DELETE /asignaturas/1.json
  def destroy
    @asignatura.destroy
    respond_to do |format|
      format.html { redirect_to asignaturas_url, notice: 'La asignatura fue eliminada.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_asignatura
      @asignatura = Asignatura.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def asignatura_params
      params.require(:asignatura).permit(:nombre)
    end
end

app/helpers/asignaturas_helper.rb
module AsignaturasHelper
end

app/views/asignaturas/_form.html.erb
<%= form_for(@asignatura) do |f| %>
  <% if @asignatura.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@asignatura.errors.count, "error") %> prohibited this asignatura from being saved:</h2>
      <ul>
        <% @asignatura.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="col-sm-4 col-sm-offset-4">
    <article class="panel panel-default">
      <section class="panel-body">
        <div class="form-group">
          <%= f.label :nombre %>
          <%= f.text_field :nombre, class:'form-control'%>
        </div>  
        <div class="actions">
          <%= f.submit %>
        </div>
      </section>
    </article>
  </div>
<% end %>

app/views/asignaturas/edit.html.erb
<div class="col-md-offset text-center">
    <div class="panel panel-default">
        <div class="panel panel-default">
             <h2 class='text text-center'>Actualizar asignatura </h2>
        </div>
        <div class="panel-body">
            <%= render 'form' %>
            <%= link_to 'Consultar', @asignatura,  class: "btn btn-default" %> 
            <%= link_to 'Volver', asignaturas_path,  class: "btn btn-default" %>
        </div>
    </div>
</div>

app/views/asignaturas/index.html.erb
<p id="notice"><%= notice %></p>
<div class="panel panel-default">
  <div class="panel-heading">
    <h2 class='text text-center'>Lista de asignaturas</h2>
  </div>
  <div class="panel-body">
    <table class= "table table-striped table-bordered">
      <thead>
        <tr>
          <th>Nombre</th>
          <th colspan="4"></th>
s        </tr>
      </thead>
      <tbody>
        <% @asignaturas.each do |asignatura| %>
          <tr>
            <td><%= asignatura.nombre %></td>
            <td>
              <div class="btn-group">
                <% if can? :destroy, @asignatura %>
                  <%= link_to 'Eliminar', asignatura, method: :delete, data: { confirm: '¿Estás seguro?' },class: 'btn btn-default' %>
                <% end %>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <% if can? :create, @asignatura %>
    <%= link_to 'Crear asignatura', new_asignatura_path, class: 'btn btn-default' %>
  <% end %>
</div>

app/views/asignaturas/new.html.erb
<div class="col-md-offset text-center">
  <div class="panel panel-default">
    <h1 class='text text-center'>Crear asignatura</h1>
  </div>
  <div class="panel-body">
    <%= render 'form' %></br></br></br></br></br></br></br></br></br>
    <%= link_to 'Vover', asignaturas_path, class: "btn btn-default" %>
  </div>
</div>

app/views/asignaturas/show.html.erb
<p id="notice"><%= notice %></p>
<div class="col-md-offset text-center">
    <div class="panel panel-default">
        <div class="panel-heading">   
            <h1 class='text text-center'>Asignatura</h1>
        </div>
        <div class="panel-heading"> 
            <h4 class='text text-center'>Nombre</h4>
        </div>
        <div class="panel-body ">
            <%= @asignatura.nombre %>
            </br>
            </br>
        </div>
    </div>
    <%= link_to 'Volver', asignaturas_path,class: "btn btn-default" %>
</div>