config/routes.rb
Rails.application.routes.draw do
  get 'users/index'

  get 'inicio/index'

  resources :grupos
  devise_for :users
  resources :asignaturas
  root 'inicio#index'

end

app/models/grupo.rb
class Grupo < ActiveRecord::Base

    belongs_to :user, :foreign_key => :alumno_id
    belongs_to :profesor, :class_name => 'user', :foreign_key => :profesor_id
    belongs_to :asignatura
    validates :alumno_id, presence: true
    validates :profesor_id , presence: true
    validates :asignatura_id, presence: true
    validates :grupo, presence: { message: "Es necesario un grupo para continuar" } 
    validates :alumno_id, uniqueness: { scope: [:profesor_id, :asignatura_id], message: "Ya existe registro de este alumno"}
    validates :calificacion, :numericality => { :greater_than_or_equal_to => 0, :less_than_or_equal_to => 10, message: ": debe ser entre un número entre 0 y 10" }

end

app/controllers/grupos_controller.rb
class GruposController < ApplicationController
  #load_and_authorize_resource
  before_action :set_grupo, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /grupos
  # GET /grupos.json

  def index
    if current_user.rol == "administrador"
          @grupos = Grupo.all.order("profesor_id asc")
        elsif current_user.rol == "alumno"
          @grupos = Grupo.where(alumno_id: current_user.id).order("grupo asc")
        elsif current_user.rol == "profesor"
          @grupos = Grupo.where(profesor_id: current_user.id).order("grupo asc")
    end
  end
  # GET /grupos/1
  # GET /grupos/1.json
  def show
  end

  # GET /grupos/new
  def new
    @grupo = Grupo.new
  end

  # GET /grupos/1/edit
  def edit
  end

  # POST /grupos
  # POST /grupos.json
  def create
    @grupo = Grupo.new(grupo_params)

    respond_to do |format|
      if @grupo.save
        format.html { redirect_to @grupo, notice: 'El grupo ha sido creado.' }
        format.json { render :show, status: :created, location: @grupo }
      else
        format.html { render :new }
        format.json { render json: @grupo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /grupos/1
  # PATCH/PUT /grupos/1.json
  def update
    respond_to do |format|
      if @grupo.update(grupo_params)
        format.html { redirect_to @grupo, notice: 'El grupo fue actualizado correctamente.' }
        format.json { render :show, status: :ok, location: @grupo }
      else
        format.html { render :edit }
        format.json { render json: @grupo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /grupos/1
  # DELETE /grupos/1.json
  def destroy
    @grupo.destroy
    respond_to do |format|
      format.html { redirect_to grupos_url, notice: 'El grupo ha sido eliminado.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_grupo
      @grupo = Grupo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def grupo_params
      params.require(:grupo).permit(:alumno_id, :profesor_id, :asignatura_id, :calificacion, :grupo)
    end
   
end

app/helpers/grupos_helper.rb
module GruposHelper
end

app/views/grupos/_form.html.erb
<%= form_for(@grupo) do |f| %>
  <% if @grupo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@grupo.errors.count, "error") %> prohibited this grupo from being saved:</h2>

      <ul>
      <% @grupo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="col-sm-4 col-sm-offset-4">
    <article class="panel panel-default">
      <section class="panel-body">
        
        <% if can? :manage, @grupo %>
            <div class="field">
            <%= f.label :alumno %>
            <%= f.collection_select :alumno_id, User.where(rol:'alumno').order("apPaterno asc"), :id, :nombre_completo , {prompt: true}, {class: "form-control"} %>
          </div>
        <% end %>
          
        <% if can? :manage, @grupo %>
          <div class="field">
            <%= f.label :profesor %>
            <%= f.collection_select :profesor_id, User.where(rol:'profesor').order("apPaterno asc"), :id, :nombre_completo, {prompt: true},{class: "form-control"} %>
          </div>
        <% end %>  
        
        <% if can? :manage, @grupo %>
          <div class="field">
            <%= f.label :materia %>
            <%= f.collection_select :asignatura_id, Asignatura.all.order("nombre asc"), :id, :nombre, {prompt: true}, {class: "form-control"} %>
          </div>
        <% end %>  
          
        <% if cannot? :manage, @grupo %>
          <div class="field">
            <%= f.label :calificacion %>
            <%= f.text_field :calificacion, class:'form-control' %>
          </div>
        <% end %> 
          
        <% if can? :manage, @grupo %>
          <div class="field">
            <%= f.label :grupo %>
            <%= f.text_field :grupo, class:'form-control' %>
          </div>
        <% end %>   
          
          <div class="actions">
            <%= f.submit %>
          </div>
          
    </section>
  </article>
</div>
<% end %>

app/views/grupos/edit.html.erb
<div class="col-md-offset text-center">
  <div class="panel panel-default">
    <div class="panel-heading">   
    
      <% if can? :create, @grupos %>
        <h1 class='text text-center'>Actualizar Grupos</h1>
      <% end %>
      
      <% if cannot? :create, @grupos %>
        <h1 class='text text-center'>Actualizar calificación</h1>
      <% end %>
    </div>
    <div class="panel-body">
      <%= render 'form' %></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br>
      <%= link_to 'Consultar', @grupo, class: "btn btn-default" %> 
      <%= link_to 'Volver', grupos_path, class: "btn btn-default" %>
    </div> 
  </div>
</div>
    

app/views/grupos/index.html.erb
<p id="notice"><%= notice %></p>
<div class="panel panel-default">
  <div class="panel-heading"> 
    <% if can? :manage, @grupos %>
      <h2 class='text text-center'>Lista de Grupos</h2>
    <% end %>
    <% if current_user.rol == "profesor" %>
      <h1 class='text text-center'>Registros académicos</h1>
    <% end %>
    <% if current_user.rol == "alumno" %>
      <h1 class='text text-center'>Historial académico</h1>
    <% end %>
  </div>
  <div class="panel-body">
    <table class= "table table-striped table-bordered">
      <thead>
        <tr>
          <% if can? :show, @grupo %>
            <th>Alumno</th>
          <% end %>
          <% if can? :create, @grupo %>
            <th class=text-center>Profesor</th>
          <% end %>
          <th>Asignatura</th>
          <th class=text-center>Calificación</th>
          <th class=text-center>Grupo</th>
          <% if current_user.rol != "alumno" %>
            <th colspan="4"></th>
          <% end %>
        </tr>
      </thead>
      <tbody>
        <% @grupos.each do |grupo| %>
          <tr>
            <% if can? :show, @grupo %>
              <td><%= grupo.user.nombre_completo %></td>
            <% end %>
            <% if can? :create, @grupo %>
              <td class=text-center><%= grupo.profesor_id %></td>
            <% end %>
            <td><%= grupo.asignatura.nombre %></td>
            <td class=text-center><%= grupo.calificacion %></td>
            <td class=text-center><%= grupo.grupo %></td>
            <% if current_user.rol != "alumno" %>
              <td>
                <div class="btn-group">
                  <% if can? :update, @grupo %>
                    <%= link_to 'Actualizar', edit_grupo_path(grupo), class: "btn btn-default" %>
                  <% end %>    
                  <% if can? :destroy, @grupo %> 
                    <%= link_to 'Eliminar', grupo, method: :delete, data: { confirm: '¿Estás seguro?' }, class: "btn btn-default" %>
                  <% end %>
                </div>
              </td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <% if can? :create, @grupo %>
    <%= link_to 'Crear grupo', new_grupo_path, class: 'btn btn-default'%>
  <% end %>
</div>

app/views/grupos/new.html.erb
<div class="col-md-offset text-center">
  <div class="panel panel-default">
    <div class="panel-heading">   
      <h1 class='text text-center'>Crear Grupo</h1>
    </div>
    <div class="panel-body">
      <%= render 'form' %></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br>
      <%= link_to 'Vover', grupos_path, class: "btn btn-default" %>
    </div>
  </div>
</div>

app/views/grupos/show.html.erb
<p id="notice"><%= notice %></p>
<div class="col-md-offset text-center">
 <div class="panel panel-default">
  <div class="panel-heading">
   <h3> Alumno </h3>
  </div>
  <div class="panel-body ">
   <%= @grupo.user.nombre_completo %>
  </div>
  <div class="panel-heading"> 
   <h4 class='text text-center'>Profesor</h4>
  </div>
  <div class="panel-body ">
   <%= @grupo.profesor_id %>
  </div>      
  <div class="panel-heading"> 
   <h4 class='text text-center'>Asignatura</h4>
  </div>
  <div class="panel-body ">
   <%= @grupo.asignatura.nombre %>
  </div>         
  <div class="panel-heading"> 
   <h4 class='text text-center'>Calificación</h4>
  </div>     
  <div class="panel-body ">
   <%= @grupo.calificacion %>
  </div>         
  <div class="panel-heading"> 
   <h4 class='text text-center'>Grupo</h4>
  </div>
  <div class="panel-body ">
    <%= @grupo.grupo %>
  </div>    
  <% if can? :update, @grupo %>
  <%= link_to 'Actualizar', edit_grupo_path(@grupo), class: "btn btn-default"  %> 
  <% end %>
  <%= link_to 'Volver', grupos_path, class: "btn btn-default"  %>
 </div>
</div>